# Generated by Django 6.1 on 2026-08-16 07:21

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1536, null=True
            ),
        ),
    ]
